# Making molecular graphs datasets

In [3]:
from gnnepcsaft.data import graphdataset
# !python -m gnnepcsaft.data.preprocess

In [4]:
ram = graphdataset.Ramirez('gnnepcsaft/data/ramirez2022')
ram.process()

Error for InChI: InChI=1S/ClF3/c2-1(3)4

 Python argument types in
    rdkit.Chem.rdmolfiles.MolToSmiles(NoneType)
did not match C++ signature:
    MolToSmiles(RDKit::ROMol mol, bool isomericSmiles=True, bool kekuleSmiles=False, int rootedAtAtom=-1, bool canonical=True, bool allBondsExplicit=False, bool allHsExplicit=False, bool doRandom=False)
    MolToSmiles(RDKit::ROMol mol, RDKit::SmilesWriteParams params) 


Error for InChI: InChI=1S/ClFO3/c2-1(3,4)5

 Python argument types in
    rdkit.Chem.rdmolfiles.MolToSmiles(NoneType)
did not match C++ signature:
    MolToSmiles(RDKit::ROMol mol, bool isomericSmiles=True, bool kekuleSmiles=False, int rootedAtAtom=-1, bool canonical=True, bool allBondsExplicit=False, bool allHsExplicit=False, bool doRandom=False)
    MolToSmiles(RDKit::ROMol mol, RDKit::SmilesWriteParams params) 




In [5]:
tml = graphdataset.ThermoMLDataset('gnnepcsaft/data/thermoml')
tml.process()

Error for InChI: InChI=1S/C8H15N2.C4F9O6S3/c1-4-5-10-7-6-9(3)8(10)2;5-2(6,7)20(14,15)1(21(16,17)3(8,9)10)22(18,19)4(11,12)13/h6-7H,4-5H2,1-3H3;/q+1;-1

 Python argument types in
    rdkit.Chem.rdmolfiles.MolToSmiles(NoneType)
did not match C++ signature:
    MolToSmiles(RDKit::ROMol mol, bool isomericSmiles=True, bool kekuleSmiles=False, int rootedAtAtom=-1, bool canonical=True, bool allBondsExplicit=False, bool allHsExplicit=False, bool doRandom=False)
    MolToSmiles(RDKit::ROMol mol, RDKit::SmilesWriteParams params) 


Error for InChI: InChI=1S/C15H18ClN2O5S.BF4/c1-2-8-17-9-4-3-5-14(17)23-15-7-6-13(16)12-18(15)10-11-22-24(19,20)21;2-1(3,4)5/h3-7,9,12H,2,8,10-11H2,1H3;/q+1;-1

 Python argument types in
    rdkit.Chem.rdmolfiles.MolToSmiles(NoneType)
did not match C++ signature:
    MolToSmiles(RDKit::ROMol mol, bool isomericSmiles=True, bool kekuleSmiles=False, int rootedAtAtom=-1, bool canonical=True, bool allBondsExplicit=False, bool allHsExplicit=False, bool doRandom=False)
    Mo

In [6]:
tmlpara = graphdataset.ThermoMLpara('gnnepcsaft/data/thermoml')
tmlpara.process()

ramirez dataset size: 1800
thermoml dataset size: 1277


In [7]:
ram, tml, tmlpara

(Ramirez(1797), ThermoMLDataset(2826), ThermoMLpara(2951))

In [21]:
import torch
vp = []
rho = []
for graph in tml:
  if ~torch.all(graph.vp == torch.zeros_like(graph.vp)):
    result_filter = graph.vp[:,-1] >= 0 
    vp.append(graph.vp[result_filter])
  if ~torch.all(graph.rho == torch.zeros_like(graph.rho)): 
    rho.append(graph.rho)

In [22]:
t_rho = torch.cat(rho)
t_vp = torch.cat(vp)

In [23]:
t_rho.shape, t_vp.shape

(torch.Size([178660, 5]), torch.Size([44266, 5]))

In [24]:
t_rho.mean(0), t_rho.median(0).values, t_rho.max(0).values, t_rho.min(0).values

(tensor([3.2410e+02, 1.7161e+07, 9.2986e-01, 1.0000e+00, 6.7794e+03],
        dtype=torch.float64),
 tensor([3.1315e+02, 6.2000e+06, 1.0000e+00, 1.0000e+00, 5.3249e+03],
        dtype=torch.float64),
 tensor([3.0000e+03, 3.0000e+08, 1.0000e+00, 1.0000e+00, 1.2528e+05],
        dtype=torch.float64),
 tensor([ 90.0000, 101.0000,   0.0000,   1.0000,   0.1933], dtype=torch.float64))

In [25]:
t_vp.mean(0), t_vp.median(0).values, t_vp.max(0).values, t_vp.min(0).values

(tensor([3.7593e+02, 2.0523e+05, 1.0000e+00, 3.0000e+00, 2.0523e+05],
        dtype=torch.float64),
 tensor([3.4990e+02, 8.1700e+03, 1.0000e+00, 3.0000e+00, 8.1700e+03],
        dtype=torch.float64),
 tensor([1.6280e+03, 1.1358e+07, 1.0000e+00, 3.0000e+00, 1.1358e+07],
        dtype=torch.float64),
 tensor([8.5525e+01, 5.1400e-28, 1.0000e+00, 3.0000e+00, 5.1400e-28],
        dtype=torch.float64))